web:
  build: .
  command: python /code/app/app.py
  ports:
   - "5001:5001"
  volumes:
   - .:/code
  links:
   - db
  hostname: myappserver
db:
  hostname: mysqlserver
  image: orchardup/mysql
  environment:
     MYSQL_ROOT_PASSWORD: 123
     MYSQL_DATABASE: Expense_System1
  volumes:
    - ./database:/var/lib/mysql
